// Generated by CoffeeScript 1.9.0
var getHash, load;

$(window).bind('hashchange', function(e) {
  return load(getHash());
});

getHash = function() {
  return location.hash.substr(1);
};

load = function(hash) {
  return $.get("md/" + hash + ".md", function(data) {
    return $('#markdown').html(marked(data));
  });
};

$(function() {
  var hash;
  hash = getHash();
  if (hash === '') {
    return load('welcome');
  } else {
    return load(hash);
  }
});

//# sourceMappingURL=app.js.map
