// Generated by CoffeeScript 1.9.0
var getCategory, getHash, load, loadMarkdown, selectActive;

$(window).bind('hashchange', function(e) {
  return load(getHash());
});

getHash = function() {
  return location.hash.substr(1);
};

load = function(hash) {
  var category;
  category = getCategory(hash);
  loadMarkdown(hash);
  return selectActive(hash, category);
};

loadMarkdown = function(hash) {
  return $.get("md/" + hash + ".md", function(data) {
    var $contentCol;
    $('#markdown').html(marked(data));
    $contentCol = $('#content-col');
    $contentCol.removeClass();
    if (hash === 'gallery') {
      $('.swipebox').swipebox();
      return $contentCol.addClass('col-lg-offset-3 col-lg-6');
    } else {
      return $contentCol.addClass('col-lg-offset-4 col-lg-4');
    }
  });
};

selectActive = function(hash, category) {
  var $li;
  $('li.active').removeClass('active');
  $li = $('ul.nav > li.dropdown > a#' + category).parents('li.dropdown').addClass('active');
  return $li.find('a[href="#' + hash + '"]').parents('li').addClass('active');
};

getCategory = function(hash) {
  switch (hash) {
    case 'masses':
    case 'office':
    case 'contacts':
      return 'info-basic';
    case 'announcements':
    case 'intentions':
      return 'info-current';
    case 'history':
    case 'priests':
    case 'groups':
    case 'cemetery':
    case 'gallery':
      return 'info-about';
  }
};

$(function() {
  var hash;
  hash = getHash();
  if (hash === '') {
    return load('home');
  } else {
    return load(hash);
  }
});

//# sourceMappingURL=app.js.map
